#!/usr/bin/env node
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { Command } from 'commander';
import { attachServers, BINDINGS_HEADER, detachServers } from './bindings-edit.js';
import { expandHome, loadConfig, parseTargets, resolveRegistryRoot, saveConfig, stateDir, type Config } from './config.js';
import { LoadoutError } from './errors.js';
import { importRepo } from './importer.js';
import { BINDINGS_FILE, formatProblems, loadRegistry, loadValidRegistry, SERVERS_DIR, type Registry } from './registry.js';
import { detectRepo, findGitRepos, normalizeRepoId, repoContext } from './repo.js';
import { repoStatus, syncRepo, type SyncResult } from './sync.js';
import type { RepoContext } from './types.js';
import { State } from './writer.js';

interface GlobalOpts {
  registry?: string;
}

const program = new Command();
program
  .name('loadout')
  .description('Define MCP servers once, map them to repositories, render client configs.')
  .version('0.1.0')
  .option('--registry <path>', 'registry path (default: $LOADOUT_REGISTRY or config file)');

function context(cmd: Command) {
  const config = loadConfig();
  const root = resolveRegistryRoot((cmd.optsWithGlobals() as GlobalOpts).registry, config);
  return { config, root };
}

function printWarnings(warnings: { file: string; message: string; level: string }[]) {
  if (warnings.length) console.error(formatProblems(warnings as never));
}

/** Local clones of registered repositories found under the configured workspaces. */
function localClones(registry: Registry, config: Config): { clones: RepoContext[]; notCloned: string[] } {
  if (!config.workspaces.length) {
    throw new LoadoutError('No workspaces configured. Run: loadout init --workspace <dir-with-your-repos>');
  }
  const clones: RepoContext[] = [];
  for (const dir of findGitRepos(config.workspaces)) {
    try {
      const repo = detectRepo(dir);
      if (registry.bindings.has(repo.id)) clones.push(repo);
    } catch {
      /* repo without remote: not ours */
    }
  }
  const seen = new Set(clones.map((c) => c.id));
  return { clones, notCloned: [...registry.bindings.keys()].filter((id) => !seen.has(id)) };
}

const OUTCOME_LABEL: Record<string, string> = {
  created: 'created',
  updated: 'updated',
  unchanged: 'up to date',
  replaced: 'replaced (backup: .bak)',
  conflict: 'SKIPPED — not generated by loadout (use --force to replace; a .bak is kept)',
  removed: 'removed (no servers attached)',
  kept: 'left alone (hand-written, no servers attached)',
  absent: 'nothing to generate',
};

function printSync(r: SyncResult, dryRun: boolean) {
  console.log(`${r.repo.id}  (${r.repo.root})${dryRun ? '  [dry run]' : ''}`);
  console.log(`  servers: ${r.servers.length ? r.servers.join(', ') : '(none)'}`);
  for (const f of r.files) {
    console.log(`  ${f.path.padEnd(18)} ${OUTCOME_LABEL[f.outcome]}`);
    if (f.tracked) console.log(`  ${''.padEnd(18)} ! tracked by git — run: git rm --cached ${f.path}`);
  }
  if (r.missingEnv.length) console.log(`  ! not set in this shell: ${r.missingEnv.join(', ')}`);
}

function runSync(registry: Registry, repos: RepoContext[], config: Config, opts: { force?: boolean; dryRun?: boolean }) {
  const state = State.load(stateDir());
  let conflicts = 0;
  for (const repo of repos) {
    const r = syncRepo(registry, repo, config.targets, state, opts);
    printSync(r, !!opts.dryRun);
    conflicts += r.files.filter((f) => f.outcome === 'conflict').length;
  }
  if (!opts.dryRun) state.save();
  if (conflicts) process.exitCode = 1;
}

program
  .command('init')
  .description('Write the user config (registry path, workspaces, targets); scaffold the registry if empty')
  .option('--workspace <dir...>', 'directories containing your repositories (for sync --all)')
  .option('--targets <list>', 'comma-separated clients: claude-code,cursor')
  .action((opts: { workspace?: string[]; targets?: string }, cmd: Command) => {
    const config = loadConfig();
    const flag = (cmd.optsWithGlobals() as GlobalOpts).registry;
    if (flag) config.registry = resolve(expandHome(flag));
    if (!config.registry) throw new LoadoutError('Pass --registry <path> (a clone of your registry repository)');
    if (opts.workspace) config.workspaces = opts.workspace.map((w) => resolve(expandHome(w)));
    if (opts.targets) config.targets = parseTargets(opts.targets, '--targets');
    if (!existsSync(join(config.registry, SERVERS_DIR))) {
      mkdirSync(join(config.registry, SERVERS_DIR), { recursive: true });
      console.log(`scaffolded ${join(config.registry, SERVERS_DIR)}/`);
    }
    if (!existsSync(join(config.registry, BINDINGS_FILE))) {
      writeFileSync(join(config.registry, BINDINGS_FILE), `${BINDINGS_HEADER}repositories: {}\n`);
      console.log(`scaffolded ${join(config.registry, BINDINGS_FILE)}`);
    }
    const file = saveConfig(config);
    console.log(`wrote ${file}`);
    console.log(`  registry:   ${config.registry}`);
    console.log(`  workspaces: ${config.workspaces.join(', ') || '(none — sync --all disabled)'}`);
    console.log(`  targets:    ${config.targets.join(', ')}`);
  });

program
  .command('sync')
  .description('Render MCP client configs for the current repository (or every local clone with --all)')
  .option('--all', 'sync every registered repository found under the configured workspaces')
  .option('--force', 'replace hand-written config files (a .bak copy is kept)')
  .option('--dry-run', 'show what would change without writing')
  .action((opts: { all?: boolean; force?: boolean; dryRun?: boolean }, cmd: Command) => {
    const { config, root } = context(cmd);
    const { registry, warnings } = loadValidRegistry(root);
    printWarnings(warnings);
    if (!opts.all) return runSync(registry, [detectRepo(process.cwd())], config, opts);
    const { clones, notCloned } = localClones(registry, config);
    runSync(registry, clones, config, opts);
    if (notCloned.length) console.log(`\nnot cloned under workspaces: ${notCloned.join(', ')}`);
  });

program
  .command('status')
  .description('Show whether generated configs are up to date (exit 1 if not)')
  .option('--all', 'check every registered repository found under the configured workspaces')
  .action((opts: { all?: boolean }, cmd: Command) => {
    const { config, root } = context(cmd);
    const { registry } = loadValidRegistry(root);
    const repos = opts.all ? localClones(registry, config).clones : [detectRepo(process.cwd())];
    const state = State.load(stateDir());
    const label = {
      ok: 'up to date',
      missing: 'missing — run loadout sync',
      stale: 'outdated — run loadout sync',
      modified: 'hand-written or edited — loadout sync --force to replace',
      orphan: 'no longer needed — run loadout sync',
      none: '-',
    };
    let dirty = false;
    for (const repo of repos) {
      const s = repoStatus(registry, repo, config.targets, state);
      console.log(repo.id);
      for (const f of s.files) {
        dirty ||= !['ok', 'none'].includes(f.status);
        console.log(`  ${f.path.padEnd(18)} ${label[f.status]}${f.tracked ? '  (! tracked by git)' : ''}`);
      }
    }
    if (dirty) process.exitCode = 1;
  });

function targetRepo(repoFlag: string | undefined): { repo: RepoContext; isCwd: boolean } {
  if (!repoFlag) return { repo: detectRepo(process.cwd()), isCwd: true };
  const id = normalizeRepoId(repoFlag);
  try {
    const cwd = detectRepo(process.cwd());
    if (cwd.id === id) return { repo: cwd, isCwd: true };
  } catch {
    /* not in a repo */
  }
  return { repo: repoContext(id, ''), isCwd: false };
}

program
  .command('attach')
  .description('Attach servers to a repository (edits bindings.yaml in the registry)')
  .argument('<servers...>', 'server names')
  .option('--repo <id>', 'repository id or git URL (default: current repository)')
  .option('--no-sync', 'do not re-render configs of the current repository')
  .action((servers: string[], opts: { repo?: string; sync: boolean }, cmd: Command) => {
    const { config, root } = context(cmd);
    const { registry } = loadValidRegistry(root);
    const unknown = servers.filter((s) => !registry.servers.has(s));
    if (unknown.length) {
      throw new LoadoutError(`Unknown server(s): ${unknown.join(', ')}. Available: ${[...registry.servers.keys()].join(', ')}`);
    }
    const { repo, isCwd } = targetRepo(opts.repo);
    const added = attachServers(registry.bindingsPath, repo.id, servers);
    console.log(added.length ? `attached to ${repo.id}: ${added.join(', ')}` : `${repo.id} already has: ${servers.join(', ')}`);
    const reloaded = loadRegistry(root);
    const errors = reloaded.problems.filter((p) => p.level === 'error');
    if (errors.length) {
      console.error(`bindings.yaml now has errors (e.g. a required param is missing):\n${formatProblems(errors)}`);
      process.exitCode = 1;
      return;
    }
    if (isCwd && opts.sync) runSync(reloaded.registry, [repo], config, {});
    console.log(`\nremember to commit the registry: git -C ${root} commit -am "attach ${servers.join(', ')} to ${repo.slug}"`);
  });

program
  .command('detach')
  .description('Detach servers from a repository (edits bindings.yaml in the registry)')
  .argument('<servers...>', 'server names')
  .option('--repo <id>', 'repository id or git URL (default: current repository)')
  .option('--no-sync', 'do not re-render configs of the current repository')
  .action((servers: string[], opts: { repo?: string; sync: boolean }, cmd: Command) => {
    const { config, root } = context(cmd);
    const { registry } = loadValidRegistry(root);
    const { repo, isCwd } = targetRepo(opts.repo);
    const removed = detachServers(registry.bindingsPath, repo.id, servers);
    console.log(removed.length ? `detached from ${repo.id}: ${removed.join(', ')}` : `${repo.id} has none of: ${servers.join(', ')}`);
    if (isCwd && opts.sync) runSync(loadValidRegistry(root).registry, [repo], config, {});
    if (removed.length) console.log(`\nremember to commit the registry: git -C ${root} commit -am "detach ${removed.join(', ')} from ${repo.slug}"`);
  });

program
  .command('matrix')
  .description('Show which repositories use which servers')
  .action((_opts: unknown, cmd: Command) => {
    const { root } = context(cmd);
    const { registry } = loadValidRegistry(root);
    const servers = [...registry.servers.keys()];
    const repos = [...registry.bindings.keys()];
    if (!repos.length) return console.log('No repositories in bindings.yaml yet.');
    const width = Math.max('repository'.length, ...repos.map((r) => r.length));
    console.log(['repository'.padEnd(width), ...servers].join('  '));
    for (const id of repos) {
      const used = new Set(registry.bindings.get(id)!.map((b) => b.server));
      console.log([id.padEnd(width), ...servers.map((s) => (used.has(s) ? '✓' : '·').padEnd(s.length))].join('  ').trimEnd());
    }
    const unused = servers.filter((s) => !repos.some((id) => registry.bindings.get(id)!.some((b) => b.server === s)));
    if (unused.length) console.log(`\nunused servers: ${unused.join(', ')}`);
  });

program
  .command('import')
  .description("Import the current repository's existing .mcp.json / .cursor/mcp.json into the registry")
  .option('--dry-run', 'show what would be imported without writing')
  .action((opts: { dryRun?: boolean }, cmd: Command) => {
    const { root } = context(cmd);
    const { registry } = loadValidRegistry(root);
    const repo = detectRepo(process.cwd());
    const r = importRepo(registry, repo, opts);
    console.log(`${repo.id}${opts.dryRun ? '  [dry run]' : ''}`);
    console.log(`  read:     ${r.sources.join(', ')}`);
    console.log(`  new:      ${r.created.join(', ') || '-'}`);
    console.log(`  existing: ${r.reused.join(', ') || '-'}`);
    console.log(`  attached: ${r.attached.join(', ') || '-'}`);
    for (const n of r.notes) console.log(`  ! ${n}`);
    if (!opts.dryRun) {
      console.log('\nnext:');
      console.log(`  1. review & commit the registry:  git -C ${root} status`);
      console.log('  2. replace the hand-written files: loadout sync --force   (backups: *.bak)');
      console.log('  3. stop tracking them in this repo if they were committed: git rm --cached <file>');
    }
  });

program
  .command('validate')
  .description('Validate the registry (schemas, references, pinned versions, plaintext secrets)')
  .action((_opts: unknown, cmd: Command) => {
    const config = loadConfig();
    const root = resolveRegistryRoot((cmd.optsWithGlobals() as GlobalOpts).registry, config);
    const { registry, problems } = loadRegistry(root);
    if (problems.length) console.log(formatProblems(problems));
    const errors = problems.filter((p) => p.level === 'error').length;
    console.log(
      `${registry.servers.size} server(s), ${registry.bindings.size} repositor${registry.bindings.size === 1 ? 'y' : 'ies'}: ` +
        `${errors} error(s), ${problems.length - errors} warning(s)`,
    );
    if (errors) process.exitCode = 1;
  });

program.parseAsync(process.argv).catch((e: unknown) => {
  if (e instanceof LoadoutError) {
    console.error(`error: ${e.message}`);
    process.exit(1);
  }
  throw e;
});
