#!/usr/bin/env node
import { execFileSync, spawn } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { Command } from 'commander';
import {
  commitAdd,
  entryFromForm,
  makeRepoOnly,
  parsePairs,
  parseServerJson,
  previewAdd,
  removeServer,
  shareServer,
  type AddEntry,
} from './add.js';
import { attachServers, BINDINGS_HEADER, detachServers } from './bindings-edit.js';
import {
  defaultRegistryDir,
  expandHome,
  loadConfig,
  parseTargets,
  resolveRegistryRoot,
  saveConfig,
  stateDir,
  type Config,
} from './config.js';
import { LoadoutError } from './errors.js';
import { findImportCandidates, importRepo, ImportSession } from './importer.js';
import {
  BINDINGS_FILE,
  formatProblems,
  knownRepos,
  loadRegistry,
  loadValidRegistry,
  SERVERS_DIR,
  type Registry,
} from './registry.js';
import { detectProject, findProjects, normalizeRepoId, repoContext, workspaceOf } from './repo.js';
import { repoStatus, syncRepo, type SyncResult } from './sync.js';
import type { RepoContext } from './types.js';
import { requiredParams, updateBindingParams } from './params.js';
import { startUi } from './ui-server.js';
import { State } from './writer.js';

const VERSION: string = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8')).version;

interface GlobalOpts {
  registry?: string;
}

const program = new Command();
program
  .name('loadout')
  .description('Define MCP servers once, map them to repositories, render client configs.')
  .version(VERSION)
  .option('--registry <path>', 'registry path (default: $LOADOUT_REGISTRY or config file)');

/** The project in the current directory (git repository, or a plain folder inside a workspace). */
const here = () => detectProject(process.cwd(), loadConfig().workspaces);

function context(cmd: Command) {
  const config = loadConfig();
  const root = resolveRegistryRoot((cmd.optsWithGlobals() as GlobalOpts).registry, config);
  return { config, root };
}

function printWarnings(warnings: { file: string; message: string; level: string }[]) {
  if (warnings.length) console.error(formatProblems(warnings as never));
}

/** Local clones of registered repositories found under the configured workspaces. */
function localClones(registry: Registry, config: Config): { clones: RepoContext[]; notCloned: string[] } {
  if (!config.workspaces.length) {
    throw new LoadoutError('No workspaces configured. Run: loadout init --workspace <dir-with-your-repos>');
  }
  const clones: RepoContext[] = [];
  for (const repo of findProjects(config.workspaces)) {
    if (knownRepos(registry).includes(repo.id)) clones.push(repo);
  }
  const seen = new Set(clones.map((c) => c.id));
  return { clones, notCloned: knownRepos(registry).filter((id) => !seen.has(id)) };
}

const OUTCOME_LABEL: Record<string, string> = {
  created: 'created',
  updated: 'updated',
  unchanged: 'up to date',
  replaced: 'replaced (backup: .bak)',
  conflict: 'SKIPPED — not generated by loadout (use --force to replace; a .bak is kept)',
  removed: 'removed (no servers attached)',
  kept: 'left alone (hand-written, no servers attached)',
  absent: 'nothing to generate',
};

function printSync(r: SyncResult, dryRun: boolean) {
  console.log(`${r.repo.id}  (${r.repo.root})${dryRun ? '  [dry run]' : ''}`);
  console.log(`  servers: ${r.servers.length ? r.servers.join(', ') : '(none)'}`);
  for (const f of r.files) {
    console.log(`  ${f.path.padEnd(18)} ${OUTCOME_LABEL[f.outcome]}`);
    if (f.tracked) console.log(`  ${''.padEnd(18)} ! tracked by git — run: git rm --cached ${f.path}`);
  }
  if (r.missingEnv.length) console.log(`  ! not set in this shell: ${r.missingEnv.join(', ')}`);
}

function runSync(registry: Registry, repos: RepoContext[], config: Config, opts: { force?: boolean; dryRun?: boolean }) {
  const state = State.load(stateDir());
  let conflicts = 0;
  for (const repo of repos) {
    const r = syncRepo(registry, repo, config.targets, state, opts);
    printSync(r, !!opts.dryRun);
    conflicts += r.files.filter((f) => f.outcome === 'conflict').length;
  }
  if (!opts.dryRun) state.save();
  if (conflicts) process.exitCode = 1;
}

program
  .command('init')
  .description('Write the user config (registry path, workspaces, targets); clone or scaffold the registry')
  .option('--from <git-url>', 'clone the registry from this git URL first (default location: ~/.local/share/loadout/registry)')
  .option('--workspace <dir...>', 'directories containing your repositories (for sync --all)')
  .option('--targets <list>', 'comma-separated clients: claude-code,cursor')
  .addHelpText(
    'after',
    `
Examples:
  loadout init --from https://github.com/ntbang0901/mcp-registry.git --workspace ~/code
  loadout init --registry ~/code/mcp-registry --workspace ~/code      # registry already cloned`,
  )
  .action((opts: { from?: string; workspace?: string[]; targets?: string }, cmd: Command) => {
    const config = loadConfig();
    const flag = (cmd.optsWithGlobals() as GlobalOpts).registry;
    if (flag) config.registry = resolve(expandHome(flag));
    if (opts.from) {
      const target = flag ? config.registry! : (config.registry ?? defaultRegistryDir());
      if (existsSync(join(target, '.git'))) {
        console.log(`registry already cloned at ${target}`);
      } else {
        if (existsSync(target) && readdirSync(target).length) throw new LoadoutError(`${target} exists and is not empty`);
        mkdirSync(dirname(target), { recursive: true });
        try {
          execFileSync('git', ['clone', opts.from, target], { stdio: 'inherit' });
        } catch {
          throw new LoadoutError(`git clone ${opts.from} failed`);
        }
      }
      config.registry = target;
    }
    if (!config.registry)
      throw new LoadoutError('Pass --from <git-url> to clone your registry, or --registry <path> to an existing clone');
    if (opts.workspace) config.workspaces = opts.workspace.map((w) => resolve(expandHome(w)));
    if (opts.targets) config.targets = parseTargets(opts.targets, '--targets');
    if (!existsSync(join(config.registry, SERVERS_DIR))) {
      mkdirSync(join(config.registry, SERVERS_DIR), { recursive: true });
      console.log(`scaffolded ${join(config.registry, SERVERS_DIR)}/`);
    }
    if (!existsSync(join(config.registry, BINDINGS_FILE))) {
      writeFileSync(join(config.registry, BINDINGS_FILE), `${BINDINGS_HEADER}repositories: {}\n`);
      console.log(`scaffolded ${join(config.registry, BINDINGS_FILE)}`);
    }
    const file = saveConfig(config);
    console.log(`wrote ${file}`);
    console.log(`  registry:   ${config.registry}`);
    console.log(`  workspaces: ${config.workspaces.join(', ') || '(none — sync --all disabled)'}`);
    console.log(`  targets:    ${config.targets.join(', ')}`);
  });

program
  .command('sync')
  .description('Render MCP client configs for the current repository (or every local clone with --all)')
  .option('--all', 'sync every registered repository found under the configured workspaces')
  .option('--force', 'replace hand-written config files (a .bak copy is kept)')
  .option('--dry-run', 'show what would change without writing')
  .action((opts: { all?: boolean; force?: boolean; dryRun?: boolean }, cmd: Command) => {
    const { config, root } = context(cmd);
    const { registry, warnings } = loadValidRegistry(root);
    printWarnings(warnings);
    if (!opts.all) return runSync(registry, [here()], config, opts);
    const { clones, notCloned } = localClones(registry, config);
    runSync(registry, clones, config, opts);
    if (notCloned.length) console.log(`\nnot cloned under workspaces: ${notCloned.join(', ')}`);
  });

program
  .command('status')
  .description('Show whether generated configs are up to date (exit 1 if not)')
  .option('--all', 'check every registered repository found under the configured workspaces')
  .action((opts: { all?: boolean }, cmd: Command) => {
    const { config, root } = context(cmd);
    const { registry } = loadValidRegistry(root);
    const repos = opts.all ? localClones(registry, config).clones : [here()];
    const state = State.load(stateDir());
    const label = {
      ok: 'up to date',
      missing: 'missing — run loadout sync',
      stale: 'outdated — run loadout sync',
      modified: 'hand-written or edited — loadout sync --force to replace',
      orphan: 'no longer needed — run loadout sync',
      none: '-',
    };
    let dirty = false;
    for (const repo of repos) {
      const s = repoStatus(registry, repo, config.targets, state);
      console.log(repo.id);
      for (const f of s.files) {
        dirty ||= !['ok', 'none'].includes(f.status);
        console.log(`  ${f.path.padEnd(18)} ${label[f.status]}${f.tracked ? '  (! tracked by git)' : ''}`);
      }
    }
    if (dirty) process.exitCode = 1;
  });

function targetRepo(repoFlag: string | undefined): { repo: RepoContext; isCwd: boolean } {
  if (!repoFlag) return { repo: here(), isCwd: true };
  const id = normalizeRepoId(repoFlag);
  try {
    const cwd = here();
    if (cwd.id === id) return { repo: cwd, isCwd: true };
  } catch {
    /* not in a repo */
  }
  return { repo: repoContext(id, ''), isCwd: false };
}

program
  .command('attach')
  .description('Attach servers to a repository (edits bindings.yaml in the registry)')
  .argument('<servers...>', 'server names')
  .option('--repo <id>', 'repository id or git URL (default: current repository)')
  .option('--no-sync', 'do not re-render configs of the current repository')
  .action((servers: string[], opts: { repo?: string; sync: boolean }, cmd: Command) => {
    const { config, root } = context(cmd);
    const { registry } = loadValidRegistry(root);
    const { repo, isCwd } = targetRepo(opts.repo);
    const own = servers.filter((s) => registry.repoServers.get(repo.id)?.has(s));
    if (own.length) throw new LoadoutError(`${own.join(', ')}: already active for ${repo.id} as repository-only server(s)`);
    const unknown = servers.filter((s) => !registry.servers.has(s));
    if (unknown.length) {
      throw new LoadoutError(
        `Unknown shared server(s): ${unknown.join(', ')}. Available: ${[...registry.servers.keys()].join(', ')}`,
      );
    }
    for (const s of servers) {
      const required = requiredParams(registry.servers.get(s)!);
      const has = registry.bindings.get(repo.id)?.some((b) => b.server === s);
      if (required.length && !has) {
        throw new LoadoutError(
          `${s} needs values for ${required.join(', ')}. Use: loadout set ${s} ${required.map((r) => `${r}=…`).join(' ')} --attach`,
        );
      }
    }
    const added = attachServers(registry.bindingsPath, repo.id, servers);
    console.log(added.length ? `attached to ${repo.id}: ${added.join(', ')}` : `${repo.id} already has: ${servers.join(', ')}`);
    const reloaded = loadRegistry(root);
    const errors = reloaded.problems.filter((p) => p.level === 'error');
    if (errors.length) {
      console.error(`bindings.yaml now has errors (e.g. a required param is missing):\n${formatProblems(errors)}`);
      process.exitCode = 1;
      return;
    }
    if (isCwd && opts.sync) runSync(reloaded.registry, [repo], config, {});
    console.log(`\nremember to commit the registry: git -C ${root} commit -am "attach ${servers.join(', ')} to ${repo.slug}"`);
  });

program
  .command('detach')
  .description('Detach servers from a repository (edits bindings.yaml in the registry)')
  .argument('<servers...>', 'server names')
  .option('--repo <id>', 'repository id or git URL (default: current repository)')
  .option('--no-sync', 'do not re-render configs of the current repository')
  .action((servers: string[], opts: { repo?: string; sync: boolean }, cmd: Command) => {
    const { config, root } = context(cmd);
    const { registry } = loadValidRegistry(root);
    const { repo, isCwd } = targetRepo(opts.repo);
    const removed = detachServers(registry.bindingsPath, repo.id, servers);
    console.log(
      removed.length ? `detached from ${repo.id}: ${removed.join(', ')}` : `${repo.id} has none of: ${servers.join(', ')}`,
    );
    if (isCwd && opts.sync) runSync(loadValidRegistry(root).registry, [repo], config, {});
    if (removed.length)
      console.log(
        `\nremember to commit the registry: git -C ${root} commit -am "detach ${removed.join(', ')} from ${repo.slug}"`,
      );
  });

program
  .command('set')
  .description("Set a repository's param values for a shared server (no values: show them)")
  .argument('<server>', 'shared server name')
  .argument('[assignments...]', 'key=value pairs (secrets: key=env://VAR_NAME)')
  .option('--unset <keys...>', 'params to remove (fall back to the default)')
  .option('--repo <id>', 'repository id or git URL (default: current repository)')
  .option('--attach', 'attach the server first if needed')
  .option('--no-sync', 'do not re-render configs of the current repository')
  .addHelpText('after', '\nExample:\n  loadout set postgres database=promotion_db password=env://PROMO_DB_PASSWORD')
  .action(
    (
      server: string,
      assignments: string[],
      opts: { unset?: string[]; repo?: string; attach?: boolean; sync: boolean },
      cmd: Command,
    ) => {
      const { config, root } = context(cmd);
      const { registry } = loadValidRegistry(root);
      const { repo, isCwd } = targetRepo(opts.repo);
      const def = registry.servers.get(server);
      if (!assignments.length && !opts.unset?.length) {
        if (!def) throw new LoadoutError(`Unknown shared server "${server}"`);
        const values = registry.bindings.get(repo.id)?.find((b) => b.server === server)?.params ?? {};
        const specs = Object.entries(def.params ?? {});
        if (!specs.length) return console.log(`${server} has no params`);
        console.log(`${server} @ ${repo.id}`);
        for (const [name, spec] of specs) {
          const value =
            values[name] !== undefined
              ? String(values[name])
              : spec.default !== undefined
                ? `(default: ${spec.default})`
                : spec.required
                  ? '(REQUIRED, not set)'
                  : '(not set)';
          console.log(
            `  ${name.padEnd(16)} ${spec.type.padEnd(8)} ${value}${spec.description ? `   # ${spec.description}` : ''}`,
          );
        }
        return;
      }
      const values: Record<string, unknown> = {};
      for (const a of assignments) {
        const i = a.indexOf('=');
        if (i <= 0) throw new LoadoutError(`Expected key=value, got "${a.slice(0, 20)}"`);
        values[a.slice(0, i)] = a.slice(i + 1);
      }
      for (const k of opts.unset ?? []) values[k] = '';
      const params = updateBindingParams(registry, repo.id, server, values, { attach: opts.attach });
      console.log(
        `${server} @ ${repo.id}: ${
          Object.entries(params)
            .map(([k, v]) => `${k}=${v}`)
            .join(' ') || '(defaults)'
        }`,
      );
      if (isCwd && opts.sync) runSync(loadValidRegistry(root).registry, [repo], config, {});
    },
  );

program
  .command('matrix')
  .description('Show which repositories use which servers')
  .action((_opts: unknown, cmd: Command) => {
    const { root } = context(cmd);
    const { registry } = loadValidRegistry(root);
    const servers = [...registry.servers.keys()];
    const repos = knownRepos(registry);
    if (!repos.length) return console.log('No repositories in the registry yet.');
    const width = Math.max('repository'.length, ...repos.map((r) => r.length));
    console.log(['repository'.padEnd(width), ...servers, 'repo-only'].join('  '));
    for (const id of repos) {
      const used = new Set((registry.bindings.get(id) ?? []).map((b) => b.server));
      const own = [...(registry.repoServers.get(id)?.keys() ?? [])].join(', ');
      console.log(
        [id.padEnd(width), ...servers.map((s) => (used.has(s) ? '✓' : '·').padEnd(s.length)), own].join('  ').trimEnd(),
      );
    }
    const unused = servers.filter((s) => !repos.some((id) => registry.bindings.get(id)?.some((b) => b.server === s)));
    if (unused.length) console.log(`\nunused servers: ${unused.join(', ')}`);
  });

program
  .command('import')
  .description('Import hand-written .mcp.json / .cursor/mcp.json into the registry (current repository, or --all)')
  .option('--all', 'scan the configured workspaces and import every project with a hand-written MCP config')
  .option('--dir <folders...>', 'scan these folders instead (implies --all; each is added to your workspaces)')
  .option('--repo-only', "import as each repository's own servers (repos/<repo>/) instead of shared ones")
  .option('--sync', 'then replace the hand-written files with generated ones (a .bak is kept)')
  .option('--dry-run', 'show what would be imported without writing')
  .addHelpText(
    'after',
    `
A server name that already exists with the same definition is reused. A different definition
replaces the shared one when no repository uses it yet; otherwise it is kept as that repository's
own server, so no repository silently switches to another one's configuration.`,
  )
  .action((opts: { all?: boolean; dir?: string[]; dryRun?: boolean; repoOnly?: boolean; sync?: boolean }, cmd: Command) => {
    const { config, root } = context(cmd);
    let scan = config.workspaces;
    if (opts.dir) {
      opts.all = true;
      scan = opts.dir.map((d) => resolve(expandHome(d)));
      for (const d of scan) {
        if (!existsSync(d)) throw new LoadoutError(`${d} does not exist`);
        // A folder inside an existing workspace is only scanned: adding it would change the ids of its projects.
        if (!opts.dryRun && !workspaceOf(d, config.workspaces)) {
          config.workspaces.push(d);
          saveConfig(config);
          console.log(`added workspace: ${d}`);
        }
      }
    }
    const { registry } = loadValidRegistry(root);
    const state = State.load(stateDir());
    let repos: RepoContext[];
    if (opts.all) {
      if (!scan.length)
        throw new LoadoutError('No workspaces configured. Pass --dir <folder>, or run: loadout init --workspace <dir>');
      const idBase = [...new Set([...config.workspaces, ...scan])];
      repos = findImportCandidates(registry, scan, state, idBase).map((c) => c.repo);
      if (!repos.length) return console.log(`No hand-written MCP configs found under ${scan.join(', ')}`);
    } else {
      repos = [here()];
    }
    const session = new ImportSession(registry, { dryRun: opts.dryRun, state });
    const imported: RepoContext[] = [];
    let failed = 0;
    for (const repo of repos) {
      let r;
      try {
        r = importRepo(registry, repo, { ...opts, session });
      } catch (e) {
        if (!opts.all) throw e;
        console.log(`${repo.id}\n  ! skipped: ${(e as Error).message}`);
        failed++;
        continue;
      }
      imported.push(repo);
      const list = (xs: string[]) => xs.join(', ') || '-';
      console.log(`${repo.id}${opts.dryRun ? '  [dry run]' : ''}`);
      console.log(`  read:      ${r.sources.join(', ')}`);
      if (r.created.length) console.log(`  new:       ${list(r.created)}`);
      if (r.reused.length) console.log(`  existing:  ${list(r.reused)}`);
      if (r.replaced.length) console.log(`  replaced:  ${list(r.replaced)}  (unused shared definition updated)`);
      if (r.own.length) console.log(`  own:       ${list(r.own)}  (repos/${repo.id}/)`);
      if (!opts.repoOnly) console.log(`  attached:  ${list(r.attached)}`);
      for (const n of r.notes) console.log(`  ! ${n}`);
    }
    if (opts.all)
      console.log(
        `\n${imported.length} repositor${imported.length === 1 ? 'y' : 'ies'} imported${failed ? `, ${failed} skipped` : ''}`,
      );
    if (opts.dryRun || !imported.length) return;
    if (opts.sync) {
      console.log('');
      runSync(loadValidRegistry(root).registry, imported, config, { force: true });
    }
    console.log('\nnext:');
    console.log(`  - review & commit the registry:  git -C ${root} status`);
    if (!opts.sync)
      console.log(`  - replace the hand-written files: loadout sync ${opts.all ? '--all ' : ''}--force   (backups: *.bak)`);
    console.log('  - in each repository, stop tracking them if they were committed: git rm --cached .mcp.json .cursor/mcp.json');
  });

interface AddOpts {
  json?: string;
  url?: string;
  header?: string[];
  env?: string[];
  description?: string;
  attach?: boolean;
  repo?: string;
  repoOnly?: boolean;
  overwrite?: boolean;
  dryRun?: boolean;
}

program
  .command('add')
  .description('Add MCP server(s) to the registry from pasted JSON, a URL, or a command')
  .argument('[name]', 'server name (optional when the JSON names its servers)')
  .argument('[command...]', 'local server command, after --  (e.g. -- uvx code-graph-mcp==1.2.4)')
  .option('--json <text>', 'MCP JSON config ({"mcpServers": ...} or one entry); also read from stdin')
  .option('--url <url>', 'remote (HTTP) server URL')
  .option('--header <k=v...>', 'HTTP header for --url (secrets become env vars)')
  .option('--env <k=v...>', 'environment variable for a command (secrets become env vars)')
  .option('--description <text>', 'description')
  .option('--attach', 'also attach to the current repository (or --repo) and sync it')
  .option('--repo <id>', 'repository to attach to (implies --attach), or owner of a --repo-only server')
  .option('--repo-only', "make it the repository's own server (repos/<repo>/), not shared")
  .option('--overwrite', 'replace an existing server definition')
  .option('--dry-run', 'print the generated definition without writing')
  .addHelpText(
    'after',
    `
Examples:
  pbpaste | loadout add                              # JSON copied from a README
  loadout add context7 --url https://mcp.context7.com/mcp
  loadout add linkup --url https://mcp.linkup.so/mcp --header "Authorization=Bearer sk-..."
  loadout add code-graph -- uvx code-graph-mcp==1.2.4 --project-root .
  loadout add db --repo-only -- npx -y @acme/pg-mcp@1.0.0     # only for the current repository`,
  )
  .action((name: string | undefined, command: string[], opts: AddOpts, cmd: Command) => {
    const { config, root: registryRoot } = context(cmd);
    const { registry } = loadValidRegistry(registryRoot);
    let entries: AddEntry[];
    if (opts.url) {
      entries = [entryFromForm({ name: name ?? '', kind: 'remote', url: opts.url, pairs: opts.header })];
    } else if (command.length) {
      entries = [
        { name, cfg: { command: command[0], args: command.slice(1), ...(opts.env ? { env: parsePairs(opts.env) } : {}) } },
      ];
    } else {
      const text = opts.json ?? (process.stdin.isTTY ? '' : readFileSync(0, 'utf8'));
      if (!text.trim())
        throw new LoadoutError('Give --json, --url, a command after --, or pipe JSON on stdin. See: loadout add --help');
      entries = parseServerJson(text);
    }
    let root: string | undefined; // absolute paths inside the current repo become {{ repo.root }}
    try {
      root = here().root;
    } catch {
      /* not in a repository */
    }
    const owner = opts.repoOnly ? targetRepo(opts.repo) : undefined;
    const preview = previewAdd(registry, entries, { name, description: opts.description, root, repo: owner?.repo.id });
    for (const s of preview.servers) {
      console.log(`--- ${s.path}${s.exists ? (opts.overwrite ? '  (replaces existing)' : '  (ALREADY EXISTS)') : ''}`);
      console.log(s.yaml.trimEnd());
      for (const p of s.problems) console.log(`  ${p.level}: ${p.message}`);
    }
    for (const n of preview.notes) console.log(`! ${n}`);
    if (opts.dryRun) return;
    const written = commitAdd(registry, preview, { overwrite: opts.overwrite });
    console.log(`\nadded: ${written.join(', ')}`);
    const envVars = [...new Set(preview.servers.flatMap((s) => s.envVars))];
    if (envVars.length) console.log(`export in your shell: ${envVars.join(', ')}`);
    if (owner) {
      console.log(`active for ${owner.repo.id} only`);
      if (owner.isCwd) runSync(loadValidRegistry(registryRoot).registry, [owner.repo], config, {});
    } else if (opts.attach || opts.repo) {
      const { repo, isCwd } = targetRepo(opts.repo);
      const added = attachServers(registry.bindingsPath, repo.id, written);
      console.log(`attached to ${repo.id}: ${added.join(', ') || '(already attached)'}`);
      if (isCwd) runSync(loadValidRegistry(registryRoot).registry, [repo], config, {});
    }
    console.log(
      `\nremember to commit the registry: git -C ${registryRoot} add -A && git -C ${registryRoot} commit -m "add ${written.join(', ')}"`,
    );
  });

program
  .command('remove')
  .description('Delete a shared server (must not be attached anywhere), or a repository-only server with --repo')
  .argument('<name>', 'server name')
  .option('--repo <id>', "delete this repository's own server (default: current repository if it has one)")
  .action((name: string, opts: { repo?: string }, cmd: Command) => {
    const { root } = context(cmd);
    const { registry } = loadValidRegistry(root);
    let repo = opts.repo ? normalizeRepoId(opts.repo) : undefined;
    if (!repo && !registry.servers.has(name)) {
      try {
        const cwd = here().id;
        if (registry.repoServers.get(cwd)?.has(name)) repo = cwd;
      } catch {
        /* not in a repository */
      }
    }
    removeServer(registry, name, repo);
    console.log(`removed ${repo ? `repos/${repo}` : 'servers'}/${name}.yaml`);
  });

program
  .command('share')
  .description("Turn a repository's own server into a shared one (it stays attached to that repository)")
  .argument('<name>', 'server name')
  .option('--repo <id>', 'owning repository (default: current repository)')
  .action((name: string, opts: { repo?: string }, cmd: Command) => {
    const { root } = context(cmd);
    const { repo } = targetRepo(opts.repo);
    shareServer(loadValidRegistry(root).registry, repo.id, name);
    console.log(`moved repos/${repo.id}/${name}.yaml → servers/${name}.yaml (still attached to ${repo.id})`);
  });

program
  .command('unshare')
  .description("Turn a shared server used by a single repository into that repository's own server")
  .argument('<name>', 'server name')
  .option('--repo <id>', 'repository that should own it (default: the one using it)')
  .action((name: string, opts: { repo?: string }, cmd: Command) => {
    const { root } = context(cmd);
    const target = makeRepoOnly(loadValidRegistry(root).registry, name, opts.repo ? normalizeRepoId(opts.repo) : undefined);
    console.log(`moved servers/${name}.yaml → repos/${target}/${name}.yaml`);
  });

program
  .command('ui')
  .description('Open a local web UI to add servers and attach them to repositories')
  .option('--port <port>', 'port to listen on (0 = random)', '4870')
  .option('--no-open', 'do not open a browser')
  .action(async (opts: { port: string; open: boolean }, cmd: Command) => {
    const { config, root } = context(cmd);
    const port = Number(opts.port);
    if (!Number.isInteger(port) || port < 0 || port > 65535) throw new LoadoutError(`Invalid port "${opts.port}"`);
    let ui;
    try {
      ui = await startUi({ registryRoot: root, config, port });
    } catch (e) {
      if ((e as { code?: string }).code === 'EADDRINUSE') throw new LoadoutError(`Port ${port} is in use; try --port 0`);
      throw e;
    }
    console.log(`loadout UI for ${root}`);
    console.log(`  ${ui.url}`);
    console.log('  (local only; the token in the URL is required. Ctrl+C to stop)');
    if (opts.open) {
      const [bin, args] =
        process.platform === 'darwin'
          ? ['open', [ui.url]]
          : process.platform === 'win32'
            ? ['cmd', ['/c', 'start', '', ui.url]]
            : ['xdg-open', [ui.url]];
      spawn(bin, args as string[], { stdio: 'ignore', detached: true })
        .on('error', () => {})
        .unref();
    }
  });

program
  .command('validate')
  .description('Validate the registry (schemas, references, pinned versions, plaintext secrets)')
  .action((_opts: unknown, cmd: Command) => {
    const config = loadConfig();
    const root = resolveRegistryRoot((cmd.optsWithGlobals() as GlobalOpts).registry, config);
    const { registry, problems } = loadRegistry(root);
    if (problems.length) console.log(formatProblems(problems));
    const errors = problems.filter((p) => p.level === 'error').length;
    console.log(
      `${registry.servers.size} shared server(s), ${[...registry.repoServers.values()].reduce((n, m) => n + m.size, 0)} repo-only, ` +
        `${knownRepos(registry).length} repositor${knownRepos(registry).length === 1 ? 'y' : 'ies'}: ` +
        `${errors} error(s), ${problems.length - errors} warning(s)`,
    );
    if (errors) process.exitCode = 1;
  });

program.parseAsync(process.argv).catch((e: unknown) => {
  if (e instanceof LoadoutError) {
    console.error(`error: ${e.message}`);
    process.exit(1);
  }
  throw e;
});
